spring.application.name: employee-api
server.port: 8111

mockEmployeeServer:
  port: 8112
  host: http://localhost
  base-url: /api/v1/

rateLimiter:
  enabled: true
  permitsPerSecond: 5                  # Number of requests allowed per second
  retry:
    maxAttempts: 5                    # Maximum retry attempts on rate limit hit
    initialBackoffMillis: 100         # Initial backoff time in milliseconds
    backoffMultiplier: 2              # Exponential backoff multiplier
    maxBackoffMillis: 2000            # Maximum backoff time in milliseconds
logging:
  level:
    root: INFO
    com.reliaquest.api: DEBUG